In [1]:
import numpy as np
import pandas as pd
import csv

## Rope Equal Parts

In [16]:
rope_parts = np.linspace(0, 5, num = 9) #By default end-point is True.
print(rope_parts)
rope_part = np.round(rope_parts, decimals = 2)
print(rope_part)
# rope_part 

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]
[0.   0.62 1.25 1.88 2.5  3.12 3.75 4.38 5.  ]


## Print Elements

In [17]:
array = np.arange(1,21, dtype = int)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
array_2d = np.array(array).reshape(4,5)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
print(array_2d[2,0:3])
print(array_2d[1:4,3])
print(array_2d[2:4, 0:6])
print(array_2d[1:3, 1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


## Non Zero Elements

In [20]:
arr = [1,2,0,0,4,0]
arry = np.array(arr)
print(arry)
ind = np.where( arry != 0)
print(ind)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


## Multiple of 3

In [21]:
arry = np.array(arr)
ind = np.where(arry%3 == 0 )
print(ind)

(array([2, 3, 5], dtype=int64),)


## Odd elements


In [22]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arry = np.array(arr)
arry[arry%2 != 0] = -1
print(arry)

[-1  2 -1  4 -1  6 -1  8 -1 10]


# Replace Max

In [26]:
arr = [11, 2, 13, 4, 15, 6, 27, 8, 19]
arry = np.array(arr)
arry[np.where(arry.max())] = 0
arry

array([ 0,  2, 13,  4, 15,  6, 27,  8, 19])

## Negate Elements

In [27]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arry = np.array(arr)
arry[ (arry > 2) & (arry < 9)]


array([3, 4, 5, 6, 7, 8])

## Height

## Sort by Column

In [28]:
# numpy.sort(a, axis=-1(optional), kind=None(optional), order=None(optional))
ary = [[21, 20, 19, 18, 17], 
      [16, 15, 14, 13, 12],
      [11, 10, 9, 8, 7],
      [6, 5, 4, 3, 2]]
arr = np.array(ary)
arry = arr[arr[:, 1].argsort()]
print(arry)


[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


## Killed in USA

In [29]:

# terrorism_dataset = pd.read_csv("D:/[APPLIED] GATE/[CodingNinjas] All Courses/[Coding Ninjas] Machine Learning and Data Science/11. Lecture 11 - NumPy/33 - 34/terrorismData.csv")


In [30]:
# terrorism_dataset.head()

In [31]:
# terrorism_dataset.shape

In [2]:
file_obj = open("D:/[APPLIED] GATE/[CodingNinjas] All Courses/[Coding Ninjas] Machine Learning and Data Science/11. Lecture 11 - NumPy/33 - 34/terrorismData.csv", encoding ='UTF-8')
data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
country = []
attack = []
day = []
month = []
year = []
for row in data:
    killed.append(row["Killed"])
    country.append(row["Country"])
    attack.append(row["AttackType"])
    day.append(row["Day"])
    month.append(row["Month"])
    year.append(row["Year"])

np_killed = np.array(killed)
np_killed[np_killed == '' ] = '0.0'


np_killed = np.array(np_killed, dtype = float)
np_country = np.array(country)
print(np_country)

bool_arr = np_country == 'United States'  
np_killed[bool_arr]

np_killed = np.array(np_killed, dtype = int)
print(np_killed)
print(np.sum(np_killed))


['Dominican Republic' 'Mexico' 'Philippines' ... 'Philippines' 'India'
 'Philippines']
[1 0 1 ... 0 0 0]
411868


## Terrorism Day

In [3]:
np_attack = np.array(attack)
np_day = np.array(day, dtype = float)
np_day = np.array(np_day, dtype = int)

bool_day = np_day[(np_day > 9) & (np_day < 21)]

attack_count =np_attack[bool_day]
attack_count.size


66330

## Terrorism Date

In [45]:
np_day = np.array(day)

np_month = np.array(month)

np_year = np.array(year)





In [5]:
np_year = np.array(year)
bool_year = np_year == '2010'
year2010 = np_year[bool_year]

month_all = np_month[bool_year]
bool_month = month_all == '1'
month_january = month_all[bool_month]


day_all = np_day[bool_year]
day_jan = day_all[(day_all > '1') & (day_all < '31') ]
print(day_jan.size)




3621


## Terror Casualty Attack

In [6]:
file_obj = open("D:/[APPLIED] GATE/[CodingNinjas] All Courses/[Coding Ninjas] Machine Learning and Data Science/11. Lecture 11 - NumPy/33 - 34/terrorismData.csv", encoding ='UTF-8')
data = csv.DictReader(file_obj, skipinitialspace = True)


country = []
city = []
np_year 
np_month
np_attack
killed = []
wounded = []
terrorist_grp = []
state = []

for row in data:
    country.append(row["Country"])
    city.append(row["City"])
    killed.append(row["Killed"])
    wounded.append(row["Wounded"])
    terrorist_grp.append(row["Group"])
    state.append(row["State"])


np_country = np.array(country)
np_city = np.array(city)
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_terrorist_grp = np.array(terrorist_grp)
np_state = np.array(state)

np_killed[np_killed == ''] = '0.0'
kild = np.array(np_killed, dtype = float)

np_wounded[np_wounded == ''] = '0.0'
wound = np.array(np_wounded, dtype = float)



bool_year = np_year == '1990'
year1990 = np_year[bool_year]



all_months = np_month[bool_year]

may_july = (all_months > '4' ) & (all_months < '8' )


attacks_all_months = np_attack[bool_year]
attacks_3months = attacks_all_months[may_july]



kild = kild[bool_year]
kild_3months = kild[may_july]



wound = wound[bool_year]
wound_3months = wound[may_july]
kild_wound = kild_3months + wound_3months


terrorist_grp = np_terrorist_grp[bool_year]
grp_3months = terrorist_grp[may_july]


all_city = np_city[bool_year]
city_casualty = all_city[may_july]


max_casualty = kild_wound.max()
casualty_index = kild_wound.argmax() 

city_max_casualty = city_casualty[casualty_index]

grp_max_casualty = grp_3months[casualty_index]




print(str(int(max_casualty)) + ' ' + city_max_casualty + ' ' + grp_max_casualty)








114 Kalmunai Liberation Tigers of Tamil Eelam (LTTE)


## Terror Casualty Red

In [7]:
np_country 
bool_country = np_country == 'India'
np_india = np_country[bool_country]

np_all_city = np_city[bool_country]

np_all_state = np_state[bool_country]




np_killed = np.array(killed)
np_killed[np_killed == ''] ='0.0'

india_killed = np_killed[bool_country]
india_killed = np.array(india_killed, dtype = float)

np_wounded = np.array(wounded)
np_wounded[np_wounded == ''] = '0.0'

india_wounded = np_wounded[bool_country]
india_wounded = np.array(india_wounded, dtype = float)

bool_jharkhand = np_all_state == "Jharkhand"
np_Jharkhand = np_all_state[bool_jharkhand]


killed_jharkhand = india_killed[bool_jharkhand]
wounded_jharkhand = india_wounded[bool_jharkhand]


casualty_jharkhand = killed_jharkhand + wounded_jharkhand
jhr = casualty_jharkhand.size



bool_odisha = np_all_state == "Odisha"
np_Odisha = np_all_state[np_all_state == "Odisha"]

killed_odisha = india_killed[bool_odisha]
wounded_odisha = india_wounded[bool_odisha]


casualty_odisha = killed_odisha + wounded_odisha
odi = casualty_odisha.size

bool_andhra = np_all_state == "Andhra Pradesh"
np_Andhra = np_all_state[np_all_state == "Andra Pradesh "]

killed_andhra = india_killed[bool_andhra]
wounded_andhra = india_wounded[bool_andhra]

casualty_andhra = killed_andhra + wounded_andhra
andhra = casualty_andhra.size

bool_chhattisgarh = np_all_state == "Chhattisgarh"
np_Chhattisgarh = np_all_state[np_all_state == "Chhattisgarh"]

killed_chhattisgarh = india_killed[bool_chhattisgarh]
wounded_chhattisgarh = india_wounded[bool_chhattisgarh]

casualty_chhattisgarh = killed_chhattisgarh + wounded_chhattisgarh
ch = casualty_chhattisgarh.size


count = jhr+odi+andhra+ch
print(count)




2545


## Terror City Casualty


In [39]:
np_india
np_all_city
all_city = np_all_city != 'Unknown'

all_cities = np_all_city[all_city]


india_killed
india_wounded
casualty = india_killed + india_wounded

casualty1 = casualty.max()
city1 = all_cities[casualty.argmax()]
casualty[casualty.argmax()] = 0.0

print((city1) + ' ' + str(int(casualty1)))

casualty2 = casualty.max()
city2 = all_cities[casualty.argmax()]
casualty[casualty.argmax()] = 0.0

print(city2 + ' ' + str(int(casualty2)))

casualty3 = casualty.max()
city3 = all_cities[casualty.argmax()]
casualty[casualty.argmax()] = 0.0

print(city3 + ' ' + str(int(casualty3)))

casualty4 = casualty.max()
city4 = all_cities[casualty.argmax()]
casualty[casualty.argmax()] = 0.0

print(city4 + ' ' + str(int(casualty4)))

casualty5 = casualty.max()
city5 = all_cities[casualty.argmax()]

print(city5 + ' ' + str(int(casualty5))) ## print in the form of string
# print(city5, int(casualty5)) ## print in the str and int form



Dhubri 1005
Bastar 272
Guwahati district 255
Satnala 232
Bundu 210


## Terrorism FrequentDay

In [58]:
np_attack
np_day
value, counts = np.unique(np_day, return_counts = True )
print(value)
print(counts.max())
index = counts.argmax()
print(value[index])

frequent_day = np_day == '15'
most_frequent_day = np_day[frequent_day]

day_of_attack = np_attack[frequent_day]
day_of_attack.size

print()



['0' '1' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '2' '20' '21'
 '22' '23' '24' '25' '26' '27' '28' '29' '3' '30' '31' '4' '5' '6' '7' '8'
 '9']
6500
15


6500